language: python
python:
   - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt

services:
  #- postgresql
before_script:
  #- psql -c "CREATE DATABASE politico_test_db;" -U postgres
  #- psql -c "CREATE USER kiarie WITH PASSWORD '7194';" -U postgres
env:
  #- SECRET_KEY="butterfly" DATABASE_TEST_URL="postgres://kiarie:7194@localhost/politico_test_db"
script:
  - python -m pytest --cov=app/api
after_success:
  - coveralls
  - codecov