FORMAT: 1A
HOST: https://tonyk-politico.herokuapp.com/

# Politico v1

A web app that helps one to vote for their candidate of choice and to 
monitor electioneering process.

### The following are the useful links for this project.

##### https://kabakiantony.github.io/Politico/UI/
##### https://github.com/KabakiAntony/Politico

## Offices Collection [/api/v1/offices]

### Create a new Office [POST]

Admin user should be able to create a new office if it does not exist.

+ Request (application/json)

        {
        "name":"Presidency",
        "office_type":"National"
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/v1/offices/0

    + Body

            {
                {
                "Data": {
                "id": 0,
                "name": "Presidency",
                "office_type": "National"
                },
                "Status": 201
                }
            }

### List all Offices [GET]

A user of the system should be able to get all the offices that exist.

+ Response 200 (application/json)

        [
            {
                "Data": [
                    {
                        "id": 0,
                        "name": "Presidency",
                        "office_type": "National"
                    },
                    {
                        "id": 1,
                        "name": "Presidency",
                        "office_type": "National"
                    }
                ],
                "Status": 200
                }
        ]

## Specific Office [/api/v1/offices/{office_id}]

+ Parameters 
    + office_id (number)- Office ID in the form of an integer

### Get specific Office [GET]

A user of the system should be able to get a specific office by supplying the id 
of the office

+ Response 200 (application/json)

        [
            {
                "Data": [
                    {
                        "id": 0,
                        "name": "Presidency",
                        "office_type": "National"
                    }
                ],
                "Status": 200
                }
        ]
        
        
## Parties Collection [/api/v1/parties]

### Create a new Party [POST]

Admin user should be able to create a new party if it does not exist.

+ Request (application/json)

        {
        "name": "odm",
        "hqAddress": "Jubilee hse",
        "logoUrl": "http://localhost/myimages"
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/v1/parties/0

    + Body

            {
                {
                "Data": {
                "id": 0,
                "hqAddress": "Jubilee hse",
                "logoUrl": "http://localhost/myimages"
                },
                "Status": 201
                }
            }

### List all Parties [GET]

A user of the system should be able to get all the parties that exist.

+ Response 200 (application/json)

        [
            {
                "Data": [
                    {
                        "id": 0,
                        "hqAddress": "Jubilee hse",
                        "logoUrl": "http://localhost/myimages"
                    },
                    {
                        "id": 1,
                        "hqAddress": "Jubilee hse",
                        "logoUrl": "http://localhost/myimages"
                    }
                ],
                "Status": 200
                }
        ]