stack: python 3.7

environment:
  PY_DIR: C:\Python37-x64

clone_depth: 25

build: off

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install:
- python --version
- python -m pip install -r requirements.txt

test_script: python -m pytest -r a -v

