build: false

environment:
  matrix:
    

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.4"
      PYTHON_ARCH: "32"


init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"


